### ISSUE TITLE
Combine efforts?

### ISSUE THREAD

**Issue by ventorvar** [tkomasa/starcitizen.tools-API-Wrapper#1]
Hey man, good stuff! I have something similar that's been sitting around for a while and would love to get some like-minded people to help maintain it. Any interest in combining efforts? https://gitlab.com/scmodding/frameworks/pyrsi

**Comment by ventorvar** [comment]
ooooo i see - you're pulling from starcitizen-api which is quite different... well, the question still stands! >D

**Comment by tkomasa** [comment]
Hey man! Took a quick look and your project looks really cool. I'd love to help out and consolidate. If you want, add me on discord at Turtle-12#0001 and you can maybe fill me in on things you may want some man power on. Don't have a lot of free time right now (evidenced by how far along my own project is lol) but I'm always willing to chip in where I can.
